services:
  # Backend Service
  - type: web
    name: drifti-backend
    env: node
    nodeVersion: 18.17.0
    buildCommand: cd backend && npm ci
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: JWT_SECRET
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: TIMESCALE_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true

  # Frontend Service
  - type: web
    name: drifti-frontend
    env: node
    nodeVersion: 18.17.0
    buildCommand: cd frontend && npm ci && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: NEXT_PUBLIC_API_URL
        value: https://drifti-backend.onrender.com
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true

NEXT_PUBLIC_FIREBASE_API_KEY="your-api-key-here"
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="drifti-58b5b-d1303.firebaseapp.com"
NEXT_PUBLIC_FIREBASE_PROJECT_ID="drifti-58b5b-d1303"
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="drifti-58b5b-d1303.appspot.com"
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID="your-sender-id-here"
NEXT_PUBLIC_FIREBASE_APP_ID="your-app-id-here" 