spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/drifti}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: ${PORT:5000}
  servlet:
    context-path: /api

firebase:
  credentials:
    base64: ${FIREBASE_CREDENTIALS_BASE64:}
  database:
    url: ${FIREBASE_DATABASE_URL:}

security:
  jwt:
    secret: ${JWT_SECRET:your-secret-key}
    expiration: 86400000 # 24 hours

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
  allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
  allowed-headers: ${CORS_ALLOWED_HEADERS:Authorization,Content-Type,Accept}
  exposed-headers: Authorization

logging:
  level:
    org.springframework.security: INFO
    com.drifti: DEBUG 